name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression (2+2)
        run: expr 2 + 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v3
        with:
          name: math-result-1
          path: math-result.txt

  another-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v3
        with:
          name: math-result-1
      - name: Multiply by 2
        run: |
          value=`cat math-result.txt`
          expr $value \* 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v3
        with:
          name: math-result-2
          path: math-result.txt

  second-job:
    runs-on: ubuntu-latest
    needs: another-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v3
        with:
          name: math-result-2
      - name: Print File
        run: |
          value=`cat math-result.txt`
          echo "Final result is: $value"
